development:
  adapter: postgresql
  encoding: utf8
  username: postgres
  database: squid_development
  pool: 16
  pool_timeout: 360
  connect_timeout: 360

test:
  adapter: postgresql
  encoding: utf8
  username: postgres
  database: squid_test
  pool: 16
  pool_timeout: 360
  connect_timeout: 360
